--return {
--	"sphamba/smear-cursor.nvim",
--	opts = {
--		smear_insert_mode = true,
--		smear_between_buffers = true,
--		smear_to_cmd = true,
--		cursor_color = "#d3cdc3",
--		stiffness = 0.5,
--		trailing_stiffness = 0.5,
--		damping = 0.67,
--		matrix_pixel_threshold = 0.5,
--	},
--}
